** Rounding Numerical Values**

In [1]:
round(1.23,1)

1.2

In [2]:
round(-1.23,1)

-1.2

In [4]:
round(-1.357,2)

-1.36

In [5]:
round(1.25361,3)

1.254

In [6]:
round(2.5)

2

In [7]:
round(1.5)

2

In [8]:
a=1627731

In [9]:
round(a,-1) # rounding takes place for tens

1627730

In [10]:
round(a,-2) # rounding takes place for hundreds

1627700

In [11]:
round(a,-3) # rounding takes place for thousands

1628000

In [12]:
# if your goal is simply to output a numerical value with a certain number
# of decimal places,you don't typically need to use round(),just specify the
# desired precision when formatting

x = 1.23456
format(x,'0.2f')

'1.23'

In [13]:
format(x,'0.3f')

'1.235'

In [14]:
'value is {:0.3f}'.format(x)

'value is 1.235'

In [15]:
a=2.1
b=4.2
c=a+b
c

6.300000000000001

In [17]:
c =round(c,2)
c

6.3

** Performing Accurate Decimal Calculations**

In [18]:
from decimal import Decimal

In [19]:
a = Decimal('4.2')
b = Decimal('2.1')
a + b

Decimal('6.3')

In [20]:
print(a+b)

6.3


In [21]:
(a+b) == Decimal('6.3')

True

In [22]:
from decimal import localcontext
a = Decimal('1.3')
b = Decimal('1.7')
print(a/b)

0.7647058823529411764705882353


In [23]:
with localcontext() as ctx:
    ctx.prec=3
    print(a/b)

0.765


In [24]:
with localcontext() as ctx:
    ctx.prec=50
    print(a/b)

0.76470588235294117647058823529411764705882352941176


** Formatting Numbers for Output**

In [25]:
x = 1234.56789

In [26]:
format(x,'0.2f')

'1234.57'

In [27]:
format(x,'>10.2f')

'   1234.57'

In [28]:
format(x,'<10.2f')

'1234.57   '

In [29]:
format(x,'^10.2f')

' 1234.57  '

In [30]:
format(x,',')

'1,234.56789'

In [31]:
format(x,'0,.1f')

'1,234.6'

In [32]:
format(x,'e')

'1.234568e+03'

In [34]:
format(x,'0.2e')

'1.23e+03'

In [35]:
'The value is {:0,.2f}'.format(x)

'The value is 1,234.57'

In [36]:
x

1234.56789

In [37]:
x = format(x,',')

In [38]:
x

'1,234.56789'

In [40]:
swap_sep = {ord('.'):',',ord(','):'.'}
x.translate(swap_sep)

'1.234,56789'

** Working with Binary,Octal,and Hexadecimal Integers**

In [41]:
x = 1234

In [42]:
bin(x)

'0b10011010010'

In [43]:
oct(x)

'0o2322'

In [44]:
hex(x)

'0x4d2'

In [45]:
format(x,'b')

'10011010010'

In [46]:
format(x,'o')

'2322'

In [47]:
format(x,'x')

'4d2'

In [48]:
int('4d2',16)

1234

In [49]:
int('1001011101',2)

605

**Packing and Unpacking Large Integers from Bytes**

In [50]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [51]:
len(data)

16

In [52]:
int.from_bytes(data,'little')

69120565665751139577663547927094891008

In [53]:
int.from_bytes(data,'big')

94522842520747284487117727783387188

In [54]:
x = 94522842520747284487117727783387188

In [55]:
x.to_bytes(16,'big')

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [57]:
x.to_bytes(16,'little')

b'4\x00#\x00\x01\xef\xcd\x00\xab\x90x\x00V4\x12\x00'

** Performing Complex-Valued Math**

In [58]:
a = complex(2,4)
b = 3-5j

In [59]:
a

(2+4j)

In [60]:
b

(3-5j)

In [61]:
a.real

2.0

In [62]:
a.imag

4.0

In [63]:
a.conjugate()

(2-4j)

In [64]:
a+b

(5-1j)

In [65]:
a*b

(26+2j)

In [66]:
a/b

(-0.4117647058823529+0.6470588235294118j)

In [67]:
abs(a)

4.47213595499958

In [68]:
import cmath

In [69]:
cmath.sin(a)

(24.83130584894638-11.356612711218173j)

In [70]:
cmath.cos(a)

(-11.36423470640106-24.814651485634183j)

In [71]:
cmath.exp(a)

(-4.829809383269385-5.5920560936409816j)

In [73]:
import numpy as np
a = np.array([2+3j,4+5j,6-7j,8+9j])
a

array([2.+3.j, 4.+5.j, 6.-7.j, 8.+9.j])

In [74]:
a+2

array([ 4.+3.j,  6.+5.j,  8.-7.j, 10.+9.j])

In [75]:
np.sin(a)

array([   9.15449915  -4.16890696j,  -56.16227422 -48.50245524j,
       -153.20827755-526.47684926j, 4008.42651446-589.49948373j])

In [76]:
cmath.sqrt(-1)

1j

In [103]:
class Complex(object):
    
    def __init__(self,real,imag):
        self.__real = real
        self.__imag = imag
        
    @property
    def real(self):
        return self.__real
    
    @property
    def imag(self):
        return self.__imag
    
    def __repr__(self):
        if self.real == 0:
            return ("{0}j").format(self.imag)
        elif self.imag == 0:
            return ("{0}").format(self.real)
        elif self.imag > 0:
            return ("{0}+{1}j").format(self.real,self.imag)
        else:
            return ("{0}{1}j").format(self.real,self.imag)
    
    def __add__(self,other):
        real = self.real+other.real
        imag = self.imag+other.imag
        return Complex(real,imag)
    
    def __sub__(self,other):
        real = self.real-other.real
        imag = self.imag-other.imag
        return Complex(real,imag)
    
    def __mul__(self,other):
        real = self.real*other.real-self.imag*other.imag
        imag = self.imag*other.real+self.real*other.imag
        return Complex(real,imag)
    
    def __truediv__(self,other):
        real = (self.real*other.real+self.imag*other.imag)/(other.real**2+other.imag**2)
        imag = (self.imag*other.real-self.real*other.imag)/(other.real**2+other.imag**2)
        return Complex(real,imag)
    
    def __abs__(self):
        return (self.real**2+self.imag**2)**0.5 
    
    def conjugate(self):
        return Complex(self.real,-self.imag)

def main():
    a1 = Complex(0,1)
    print(a1)
    a2 = Complex(1,0)
    print(a2)
    a3 = Complex(2,4)
    print(a3)
    print("a3.real: ",a3.real)
    print("a3.imag: ",a3.imag)
    b = Complex(3,-5)
    print("b: ",b)
    print("b.real: ",b.real)
    print("b.imag: ",b.imag)
    print("b.conjugate: ",b.conjugate())
    print("a+b: ",a3+b)
    print("a-b: ",a3-b)
    print("a*b: ",a3*b)
    print("a/b: ",a3/b)
    print("abs({0}): {1:.3f}".format(a3,abs(a3)))

if __name__=="__main__":
    main()

1j
1
2+4j
a3.real:  2
a3.imag:  4
b:  3-5j
b.real:  3
b.imag:  -5
b.conjugate:  3+5j
a+b:  5-1j
a-b:  -1+9j
a*b:  26+2j
a/b:  -0.4117647058823529+0.6470588235294118j
abs(2+4j): 4.472


** Working with Infinity and NaNs**

In [1]:
a = float('inf')
b = float('-inf')
c = float('nan')

In [2]:
a

inf

In [3]:
b

-inf

In [4]:
c

nan

In [5]:
import math

In [6]:
math.isinf(a)

True

In [7]:
math.isnan(c)

True

In [8]:
a+45

inf

In [9]:
a*10

inf

In [10]:
10/a

0.0

** Calculating with Fractions **

In [11]:
from fractions import Fraction

In [13]:
a = Fraction(5,4)
b = Fraction(7,16)


In [14]:
print(a+b)

27/16


In [15]:
print(a*b)

35/64


In [16]:
c = a*b

In [17]:
c.numerator

35

In [18]:
c.denominator

64

In [19]:
float(c)

0.546875

In [20]:
eval("35/64")

0.546875

In [24]:
print(c.limit_denominator(7))

4/7


In [25]:
x = 3.75
y = Fraction(*x.as_integer_ratio())
y

Fraction(15, 4)

** Picking Things at Random **

In [28]:
import random

In [29]:
values = [1,2,3,4,5,6]

In [38]:
random.choice(values) # pick a random item out of a sequence

5

In [32]:
random.choice(values)

6

In [33]:
random.sample(values,2) # Take a sampling of N items 

[6, 3]

In [34]:
random.sample(values,3)

[2, 4, 6]

In [35]:
random.sample(values,4)

[2, 6, 1, 5]

In [36]:
random.shuffle(values)  # shuffle items in a sequence in place

In [37]:
values

[5, 1, 6, 3, 4, 2]

In [39]:
random.randint(0,10) # produce random integers

9

In [40]:
random.randint(0,10) # produce random integers

6

In [42]:
random.random() # produce uniform floating-point values in the range 0 to 1

0.08927063250026424

** Converting Days to Seconds, and Other Basic Time Conversions**

In [43]:
from datetime import timedelta

In [44]:
a = timedelta(days=2,hours=6)
a

datetime.timedelta(2, 21600)

In [46]:
b = timedelta(hours=4.5)
b

datetime.timedelta(0, 16200)

In [48]:
c = a+b
c

datetime.timedelta(2, 37800)

In [49]:
c.days

2

In [50]:
c.seconds

37800

In [51]:
c.seconds/3600

10.5

In [53]:
c.total_seconds()

210600.0

In [54]:
from datetime import datetime

In [55]:
a = datetime(2012,9,23)

In [56]:
print(a+timedelta(days=10))

2012-10-03 00:00:00


In [57]:
b = datetime(2012,12,21)
b

datetime.datetime(2012, 12, 21, 0, 0)

In [60]:
d = b-a
d.days

89

In [61]:
now = datetime.today()
print(now)

2018-08-06 20:52:35.171565


In [62]:
print(now + timedelta(minutes=10))

2018-08-06 21:02:35.171565


In [64]:
now.weekday()

0